apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: acm-event-exporter-config
  namespace: open-cluster-management
  annotations:
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: event-exporter-config 
        spec:
          object-templates-raw: |
            {{- /* Specify the parameters  */ -}}
            {{- $namespace := "open-cluster-management" }}   
            {{- $exporter_secret := "acm-event-exporter-secret" }} 

            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $exporter_secret }}
                  namespace: {{ $namespace }}
                type: Opaque
          remediationAction: inform
          severity: high 

---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: acm-event-exporter-config-binding
  namespace: open-cluster-management
placementRef:
  name: acm-event-exporter-config-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
- name: acm-event-exporter-config
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acm-event-exporter-config-placement 
  namespace: open-cluster-management
spec:
  clusterSets:
  - default
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - key: name
            operator: In 
            values: 
              - local-cluster
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: open-cluster-management
spec:
  clusterSet: default
