apiVersion: apps/v1
kind: Deployment
metadata:
  name: amc-event-exporter
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amc-event-exporter
  template:
    metadata:
      labels:
        name: amc-event-exporter
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --pod-namespace=$(POD_NAMESPACE)
        - --leaf-hub-name=event-exporter
        - --kafka-consumer-id=event-exporter
        - --enforce-hoh-rbac=false
        - --transport-type=kafka
        - --kafka-bootstrap-server=$(KAFKA_BOOTSTRAP_SERVERS)
        - --kafka-ca-cert-path=/kafka-certs/ca.crt
        - --kafka-client-cert-path=/kafka-certs/client.crt
        - --kafka-client-key-path=/kafka-certs/client.key
        - --kafka-consumer-topic=spec
        - --kafka-producer-topic=$(STATUS_TOPIC)
        - --kafka-event-topic=$(EVENT_TOPIC)
        - --transport-message-compression-type=gzip
        - --lease-duration=15
        - --renew-deadline=10
        - --retry-period=2
        - --enable-global-resource=true
        - --qps=150
        - --burst=300
        - --enable-pprof=false
        - --standalone=true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: acm-event-exporter-secret
              key: bootstrap.server
        - name: EVENT_TOPIC
          valueFrom:
            secretKeyRef:
              name: acm-event-exporter-secret
              key: event.topic
        - name: STATUS_TOPIC
          valueFrom:
            secretKeyRef:
              name: acm-event-exporter-secret
              key: status.topic
        image: quay.io/myan/multicluster-global-hub-agent:standalone
        imagePullPolicy: Always
        name: acm-event-exporter
        volumeMounts:
        - mountPath: /kafka-certs
          name: kafka-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: acm-event-exporter
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kafka-certs
        secret:
          defaultMode: 420
          secretName: acm-event-exporter-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acm-event-exporter 
  namespace: open-cluster-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:acm-event-exporter
  namespace: open-cluster-management
subjects:
- kind: ServiceAccount
  name: acm-event-exporter
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: open-cluster-management:acm-event-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:acm-event-exporter
rules:
- apiGroups:
  - "app.k8s.io"
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - "apps.open-cluster-management.io"
  resources:
  - channels
  - placementrules
  - subscriptionreports
  - subscriptions
  - subscriptionstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - "policy.open-cluster-management.io"
  resources:
  - placementbindings
  - policies
  - policyautomations
  - policysets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placements
  - managedclustersets
  - managedclustersetbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersets/join
  - managedclustersets/bind
  verbs:
  - create
  - delete
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclusters/finalizers
  - placementdecisions
  - placementdecisions/finalizers
  - placements
  - placements/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - configmaps
  - events
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - multiclusterhubs
  - clustermanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clusterclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - list
  - watch
  - get
 
